# Generated by Django 5.0.2 on 2025-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_addresschangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresschangerequest',
            name='field_name',
            field=models.CharField(choices=[('residential_address', 'Residential Address'), ('business_address', 'Business Address')], default='residential_address', max_length=50),
        ),
    ]
