# Generated by Django 5.0.2 on 2025-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_committeemember_entrepreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='committee_members/'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='entrepreneurs/'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
