# Generated by Django 5.0.2 on 2025-07-02 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_event_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
