# Generated by Django 5.0.2 on 2025-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newuser_added_by_newuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='pantoption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
