# Generated by Django 5.0.2 on 2025-07-02 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_pantoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='head_of_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_family', to=settings.AUTH_USER_MODEL),
        ),
    ]
