# Generated by Django 5.0.2 on 2025-07-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, default='example@mail.com', max_length=254, null=True, unique=True),
        ),
    ]
