# Generated by Django 5.0.2 on 2025-07-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_newuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
