from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path("register/", views.register_user, name="register"),
    path('login/', views.login_user, name='login'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path("add-family-member/", views.add_family_member, name="add_family_member"),
    path('get_member_details/<int:user_id>/', views.get_member_details, name='get_member_details'),
    path('admin_dashboard/', views.admin_dashboard, name= 'admin_dashboard'),
    path("edit-family-member/<int:pk>/", views.edit_family_member, name="edit_family_member"),
    path("delete-family-member/<int:pk>/", views.delete_family_member, name="delete_family_member"),
    path('event-list/', views.event_list, name='event_list'),
    path('event-list-admin/', views.event_list_admin, name='event_list_admin'),
    path('add-event/', views.add_event, name='add_event'),
    path('add-even-admin/', views.add_event_admin, name='add_event_admin'),
    path('event/update/', views.update_event, name='update_event'),
    path('event/delete/<int:event_id>/', views.soft_delete_event, name='delete_event'),
    path('get_event_details/<int:event_id>/', views.get_event_details, name='get_event_details'),
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('request-list/', views.request_list, name='search_members'),
    path('review_address_requests/', views.review_address_requests, name='review_requests'),
    path('approve/residential/<int:req_id>/', views.approve_request, name='approve_request'),
    path('reject/residential/<int:req_id>/', views.reject_request, name='reject_request'),

    path('invite/<int:event_id>/search/', views.search_members_events, name='search_members_events'),
    path('activate-user/<int:user_id>/', views.activate_user, name='activate_user'),
    path('deactivate-user/<int:user_id>/', views.deactivate_user, name='deactivate_user'),
    path('logout/', views.logout_user, name='logout'),
    path('invite/<int:event_id>/', views.invite_member, name='invite_member'),
    path('events/<int:event_id>/invite/send/', views.send_invites, name='send_invites'),
    path('events/<int:event_id>/invited-members/', views.invited_members_list, name='invited_members_list'),
    path('profile/', views.profile_view, name='profile_view'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('search-people/', views.request_list1, name='request_list1'),
    path('committeemembers/', views.committeemembers, name='committeemembers'),
    path('jainammembers/', views.jainammembers, name='jainammembers'),
    path('request-address-change/', views.request_address_change, name='request_address_change'),
    path('request-address-change1/', views.request_address_change1, name='request_address_change1'),
    path('entrepreneurs/', views.entrepreneur_list, name='entrepreneur_list'),
    path('add-entrepreneur/', views.add_entrepreneur, name='add_entrepreneur'),
    path('edit-entrepreneur/', views.edit_entrepreneur, name='edit_entrepreneur'),
    path('entrepreneur/delete/<int:pk>/', views.soft_delete_entrepreneur, name='soft_delete_entrepreneur'),
    path('add-member-admin/', views.add_member_admin, name='add_member_admin'),
    path('add_new_user/', views.add_new_user, name='add_new_user'),
    path("add-family-member-admin/", views.add_family_member_admin, name="add_family_member_admin"),

]
